formats = "ipynb,py:percent"  # Sync between .ipynb and .py (percent format)
default_jupytext_formats = "ipynb,py"  # Default pairing when saving new notebooks
cell_metadata_filter = "-all"  # Exclude all cell metadata except execution count
notebook_metadata_filter = "jupytext,text_representation"  # Only save Jupytext metadata
